export interface Jugador{
    id?:number;
    id_usuario?:number;
    id_equipo?:number;
    nombre?:string;
    apodo?:string;
    posicion1?:string;
    posicion2?:string;
    img?:string;
    tiro?:number;
    remate?:number;
    defensa?:number;
    velocidad?:number;
    gambeta?:number;
    estado_fisico?:number;
    tecnica?:number;
    rusticidad?:number;
    temperamento?:number;
    prop_lesiones?:number;
}